# -*- coding: utf-8 -*-
"""Pattern code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yZqIkz-T0ocxG2KP_41b5ytW3cMRa8OY
"""

n=5
print("* " * n)

n=5 
for i in range(n):
  print("*")

n=5 
for i in range(n):
  print("*", end= " ")

#Printing Square - no of col and rows are even 
n= int(input("Enter the number of row : ")) 
for i in range(n): 
  for j in range(n):
    print("*", end=" ")
  print()

#Rectangle  : no ofd col and rows are uneven 
n= int(input("Enter the number of row : ")) 
for i in range(n): 
  for j in range(n+1):
    print("*", end=" ")
  print()

#Rectangle  : no ofd col and rows are uneven 
n= int(input("Enter the number of row : ")) 
for i in range(n): 
  for j in range(n+2):
    print("*", end=" ")
  print()

#Increasing triangle --when i=1 it has two stars means we have to increase the row in col for loop
n= int(input("Enter the number of row : "))
for i in range(n):
  for j in range(i+1):
    print("*", end=" ")
  print()

#Increasing Optus triangle --when i=1 it has two stars means we have to increase the row in col for loop
n= int(input("Enter the number of row : "))
for i in range(n):
  for j in range(i+1):
    print("", end=" ")
  
  for j in range(i+1):
    print("*", end=" ")
  print()

#Decereasing and Increasing pattern
n=5
for i in range(n):
  for j in range(i,n):
    print(" ", end=" ")
  
  for j in range(i+1):
    print("*", end=" ")
  print()

#Increasing & decreasing pattern 
n=5 
for i in range(n):
  for j in range(i+1):
    print("& ", end=" ")

  for j in range(i,n):
    print("* ", end= " ")

  print()

n=5 
for i in range(n):
  for j in range(i+1):
    print(" ", end=" ")

  for j in range(i,n):
    print("*", end= " ")

  print()

n= int(input("Enter the number of row : "))
for i in range(n):
  for j in range(i,n):# for inverse col we need to subtract 
    print("*", end=" ")
  
  for j in range(i+1):
    print("&", end=" ")
  print()

n= int(input("Enter the number of row : "))
for i in range(n):
  for j in range(i,n):# for inverse col we need to subtract 
    print(" ", end=" ")
  
  for j in range(i+1):
    print("&", end=" ")
  print()

#Hill PAttern 
n=5
for i in range(n):

  for j in range(i,n):
    print(" ", end=" ")

  for j in range(i):
    print("*", end=" ")
  
  for j in range(i+1):
    print("*", end=" ")
  print()

#Inverse Hill pattern 
n=5
for i in range(n):

  for j in range(i+1):
    print(" ", end=" ")

  for j in range(i,n-1):
    print("*", end=" ")
  
  for j in range(i,n):
    print("*", end=" ")
  print()

#Diamond 
n=5
for i in range(n-1):

  for j in range(i,n):
    print(" ", end=" ")

  for j in range(i):
    print("*", end=" ")
  
  for j in range(i+1):
    print("*", end=" ")
  print()


for i in range(n):
  for j in range(i+1):
    print(" ", end=" ")

  for j in range(i,n-1):
    print("*", end=" ")
  
  for j in range(i,n):
    print("*", end=" ")
  print()

n= int(input("Enter the number of row : "))
for i in range(n):
  for j in range(i+1):
    print("", end=" ")
  
  for j in range(i,n-1):
    print("*", end=" ")
  print()

1#Decreasing triangle -- this means when i=0 the count of col runs till 5
#when =1 the count of col will run till 5 i.e 2,3,4,5

n= int(input("Enter the number of row : "))
for i in range(n):
  for j in range(i,n):
    print("*", end=" ")
  print()

n= int(input("Enter the number of row : "))
for i in range(n):
  for j in range(1,n+1):
    print(j, end=" ") #this will help us to print the value of j that as the per the no of row. 
  print()

n= int(input("Enter the number of row : "))
for i in range(n):
  for j in range(1,i+1):#the formula will help us to print the * as per the no of row counts
    print(j, end=" ")
  print()

n= int(input("Enter the number of row : "))
for i in range(n):
  for j in range(1,i+1):
    print(i, end=" ") #This will print the no of rows
  print()

n= int(input("Enter the number of row : "))
for i in range(n):
  for j in range(i,n): #since this is range we are doing n+1 so that we 
    print(j, end=" ")
  print()
#this will help us to inverse the bcz in col statemnet we are starting it from row and in print we are j

n= int(input("Enter the number of row : "))
for i in range(n):
  for j in range(i,n-1):#This will reduce the count of n by 2 bcz we are using range and when n-5 range will take only 4  
    print(j, end=" ")
  print()

n= int(input("Enter the number of row : "))
for i in range(n):
  for j in range(i,n-1):
    print(i, end=" ")
  print()

#*
#* *
#* * *
#* *
#*

row = int(input('Enter number of rows required: '))

for i in range(row):
  for j in range(row-i):
    print(' ', end='') # printing space required and staying in same line
    
  for j in range(2*i+1):
    print('*',end='') # printing * and staying in same line
  print()

#Hollow triangle 

n=5
for i in range(n):
  for j in range(i+1):
    if j==0 or j==i or i==n-1:
      print("*", end=" ")
    else:
      print(" ", end=" ")
  print()

n=5
for i in range(n):
  for j in range(n):
    if j==0 or j==i or i==n-1:
      print("*", end=" ")
    else:
      print(" ", end=" ")
  print()

#Square
n=5
for i in range(n+1):
    for j in range(n+1):
        if (i==0 or i==n or j==0 or j==n):
          print("*", end=" ")
        else:
          print(" ", end=" ")
    
    print()

#Rectangle
n=5
m=7
for i in range(n+1):
    for j in range(m+1):
        if (i==0 or i==n or j==0 or j==m):
          print("*", end=" ")
        else:
          print(" ", end=" ")
    
    print()

#Hollow hill 

n=5
for i in range(n):
    for j in range(i,n):
      print(" ", end=" ")

    for j in range(i):
        if (i==n-1 or j==0):
          print("*", end=" ")
        else:
          print(" ", end=" ")

    for j in range(i+1):
        if (i==n-1 or j==i):
          print("*", end=" ")
        else:
          print(" ", end=" ")
    print()

#Hollow inverted hill

n=5 
for i in range(n):
  for j in range(i+1):
    print(" ", end=" ")

  for j in range(i,n-1):
    
    if (i==n+1 or j==0 or j==i or i==0):
      print("*", end=" ")
    else:
      print(" ", end=" ")

  for j in range(i,n):
    if (i==0 or j==0 or j==n-1):
      print("*", end=" ")
    else:
      print(" ", end=" ")
  print()

#Plus sign
n=5
for i in range(n):
  for j in range(n):
    if i==n//2 or j==n//2:
      print("*", end=" ")
    else:
      print(" ", end=" ")
  print()

#Hollow Diamond

n=5
for i in range(n):
  for j in range(i,n):
    print(" ", end=" ")

  for j in range(i):
    if (i==0 or j==0):
      print("*", end=" ")
    else:
      print(" ", end=" ")
  
  
  for j in range(i+1):
    if (i==j or j==0 or i==0):
      print("*",end=" ")
    else:
      print(" ",end=" ")

  print()

for i in range(n):
  for j in range(i+1):
    print(" ", end=" ")

  for j in range(i,n):
    if (j==i or j==0 or i==0 or j==n-1):
      print("*", end=" ")
    else:
      print(" ", end=" ")

  for j in range(i,n-1):
    if (i==n or i==0 or j==n-2 or j==0):
      print("*", end=" ")
    else:
      print(" ", end=" ")
  
  print()

n=5 
for i in range(n):
  for j in range(i+1):
    print(" ", end=" ")

  for j in range(i,n):
    print("*", end=" ")
  
  for j in range(i,n-1):
    print("*", end=" ")
  
  print()

for i in range(n):
  for j in range(i, n):
    print(" ",end=" ")

  for j in range(i+1):
    print("*", end=" ")

  for j in range(i):
    print("*", end=" ")
  
  print()

#Alphabets

n=7
m=5
for i in range(n):
  for j in range(m):
    if ((j==0 or j==4) and i!=0) or ((i==0 or i==3) and (j>0 or j<4)):
      print("*", end=" ")
    else:
      print(" ", end=" ")
  print()

for i in range(7):
    for j in range(5):
      if (j==0) or (j==4 and (i!=0 and i!=3 and i!=6)) or ((i==0 or i==3 or i==6) and (j>0 and j<4)):
        print("*", end=" ")
      else:
        print(" ", end=" ")
    
    print()

for i in range(5):
  for j in range(5):
    if (j==0 or j==4) or (i==j and (j>0 or j<4)):
      print("N", end=" ")
    else:
      print(" ",end=" ")
    
  print()

for i in range(6):
  for j in range(4):
    if (j==0 and (i!=0 and i!=5)) or ((i==0 or i==5) and j>0):
      print("&", end=" ")
    
    else:
      print(" ", end=" ")
  print()

for i in range(6):
  for j in range(5):
    if (j==0) or (j==4 and (i!=0 and i!=5)):
      print("*", end=" ")
    elif((i==0 or i==5) and (j>0 and j<4)):
      print("&", end=" ")
    else:
      print(" " , end=" ")
  
  print()

for Row in range(0,7):
  for Col in range(0,7):
    if (Col == 1 or ((Row == 0 or Row == 6) and (Col > 1 and Col < 6)) or (Row == 3 and Col > 1 and Col < 5)):
      print("*", end=" ")   
    else:
      print(" ", end=" ")    
  
  print()

for Row in range(0,7):
  for Col in range(0,7):
    if (Col == 1 or ((Row == 0) and (Col > 1 and Col < 6)) or (Row == 3 and Col > 1 and Col < 5)):
      print("*", end=" ")   
    else:
      print(" ", end=" ")    
  
  print()

for Row in range(0,7):
  for Col in range(0,7):
    if (Col == 1 or ((Row == 0) and (Col > 1 and Col<5)) or (Row == 6 and Col >1 and Col<5) or (Col==5 and (Row!=1 and Row!=2)) or (Row==3 and (Col==4 or Col==6))):
      print("*", end=" ")   
    else:
      print(" ", end=" ")    
  
  print()

